### PR TITLE
Fix[NMP-703]: UI Fertigation Units

### PR DESCRIPTION
**Pull request by lunamoonmoon**
## Pull Request Standards

- [x] The title of the PR is accurate
- [x] The title includes the type of change [`HOTFIX`, `FEATURE`, `etc`]  
- [x] The PR title includes the ticket number in format of `[NMP-###]`
- [x] Documentation is updated to reflect change [`README`, `functions`, `team documents`]

# Description

This PR includes the following proposed change(s):
- Change the headings for 'Fertigation Details - Add' page
- Match 'Total Product Volume per Fertigation' and 'Total Product Volume for Growing Season' to the unit the user selects for product rate
- Round Volumes to One decimal place, time to the nearest minute (no decimals)
- Headers for N, P2O5, and K2O need to be aligned and the icons in 'Still Required This Year' should go beside the number totals
- Change 'Action' header for both Dry Fertilizer and Dry Fertilizer (Custom) to 'Solubility Assessment'
- Change output text from 'Good' to 'Soluble' and keep the green checkmark

Screenshot 2024-11-28 at 12 11 31 PM

Screenshot 2024-11-27 at 2 35 25 PM

### CODE REVIEW

**Comment by PaulGarewal** [comment]
Not sure if this is in another ticket, but may be good to get the spell check here of "fetigation" -> "fertigation" 
Also should we centre the "Time per Application" header?

**Comment by lunamoonmoon** [comment]
> Not sure if this is in another ticket, but may be good to get the spell check here of "fetigation" -> "fertigation" Also should we centre the "Time per Application" header?

Fixed fertigation typo and centered "Time per Application" header.
Screenshot 2024-12-04 at 1 18 53 PM

**Review by PaulGarewal — APPROVED** [review]
LGTM 🚀

**Review by raarielgrace — APPROVED** [review]
Paul approved, and I merged w/o making any changes, so I'm re-approving.

**Pull request merged**
